name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
    - '.github/workflows/azure-static-web-apps-white-grass-06a8fc91e.yml'
    - 'wasm-server'
    - 'HelloWorld'

jobs:
  build_wasm_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    
  # name: Build and Deploy Job
  # steps:
  #   - uses: actions/checkout@v2

  #build_and_deploy_job:
  #  needs: [build_wasm_job]  
  # The type of runner that the job will run on
  #  runs-on: windows-latest
    env:
        workingDirectory: HelloWorld
        # Steps represent a sequence of tasks that will be executed as part of the job

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.200'

      - name: Build with dotnet
        run: |
          $csproj = "HelloWorld.Wasm.csproj"
          msbuild /r /p:BuildPlatformTarget=Wasm $csproj
          msbuild /r /p:Configuration=Release $csproj  
        #"/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" 

        #cd $(build.sourcesdirectory)
        #msbuild $csproj /r /p:Configuration=Release /p:UnoSourceGeneratorUseGenerationHost=true /p:UnoSourceGeneratorUseGenerationController=false /p:OutDir=wasm-server

      - name: SWA Build and Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GRASS_06A8FC91E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "wasm-server/dist" # App source code path
          api_location: "api" # Api source code path - optional
          app_build_command: 'echo \"SWA built\"'
          #app_artifact_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GRASS_06A8FC91E }}
          action: "close"
